
USE ROLE ACCOUNTADMIN;
USE DATABASE ETF;


SELECT *
FROM TABLE(
INFORMATION_SCHEMA.QUERY_HISTORY(
    dateadd('days', -5, current_timestamp()),
    current_timestamp() 
    )
)
ORDER BY TOTAL_ELAPSED_TIME DESC;


SELECT HASH(QUERY_TEXT), QUERY_TEXT, COUNT(*),
        AVG(COMPILATION_TIME), AVG(EXECUTION_TIME)
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
     dateadd('days', -5, current_timestamp()),
    current_timestamp() 
))
GROUP BY HASH(QUERY_TEXT), QUERY_TEXT
ORDER BY COUNT(*) DESC, AVG(COMPILATION_TIME) DESC;